### ISSUE TITLE
Non-relative paths to specs cause exception

### ISSUE THREAD

**Issue by benrady** [zendeskarchive/jessie#3]
Patch coming soon. Just wanted to document the problem.

$ ./bin/jessie ~/workspace/jessie/spec
Jessie failed to start. Here's some info about the problem:
Error: ENOENT, No such file or directory '/Users/brady/workspace/jessie//Users/brady/workspace/jessie/spec'
    at Object.statSync (fs.js:400:18)
    at /Users/brady/workspace/jessie/lib/jessie/finder.js:11:21
    at Array.forEach (native)
    at [object Object].find (/Users/brady/workspace/jessie/lib/jessie/finder.js:9:19)
    at [object Object].run (/Users/brady/workspace/jessie/lib/jessie/runner.js:6:31)
    at Object.run (/Users/brady/workspace/jessie/lib/jessie.js:11:47)
    at Object.<anonymous> (/Users/brady/workspace/jessie/bin/jessie:38:10)
    at /Users/brady/workspace/jessie/node_modules/cli/cli.js:989:18
    at Object.main (/Users/brady/workspace/jessie/node_modules/cli/cli.js:994:9)
    at Object.<anonymous> (/Users/brady/workspace/jessie/bin/jessie:33:5)

**Comment by benrady** [comment]
Submitted pull request that fixes this issue
